name: strive
description: "Transform your fitness journey into an epic adventure with this interactive health app, blending gamified workouts and smart diet tracking to help you conquer your goals and climb the leaderboards!"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Assets
  animations: ^2.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # Arquitetura & Injeção de Dependência
  injectable: ^2.0.0
  get_it: ^8.0.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  go_router: ^17.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1

  # Funcionalidades de Saúde
  # CORREÇÃO: Atualizado para v13 para aceitar o novo intl
  health: ^13.0.0 
  permission_handler: ^11.0.0
  flutter_local_notifications: ^17.0.0
  wakelock_plus: ^1.2.0

  # Utilitários & Internacionalização
  shared_preferences: ^2.2.2
  
  # Mantemos o 0.20.2 que o seu FVM Flutter exige
  intl: ^0.20.2
  
  flutter_localizations:
    sdk: flutter
  slang: ^3.31.0
  slang_flutter: ^3.31.0
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  slang_build_runner: ^3.31.0
  widgetbook_generator: ^3.14.0
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

slang:
  base_locale: pt
  input_directory: lib/i18n
  input_file_pattern: .i18n.json
  output_directory: lib/i18n
  output_file_name: strings.g.dart
  namespaces: false
  translate_var: t
  enum_name: AppLocale