name: strive
description: "Transform your fitness journey into an epic adventure with this interactive health app, blending gamified workouts and smart diet tracking to help you conquer your goals and climb the leaderboards!"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  animations: ^2.0.0
  injectable: ^2.0.0
  get_it: ^8.0.0
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # Pacotes principais do Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3

  # Pacote espec√≠fico para o Google Sign-In
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  slang: ^3.31.0
  slang_flutter: ^3.31.0
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  slang_build_runner: ^3.31.0
  widgetbook_generator: ^3.14.0

flutter:
  uses-material-design: true

slang:
  base_locale: pt
  input_directory: lib/i18n
  input_file_pattern: .i18n.json
  output_directory: lib/i18n
  output_file_name: strings.g.dart
  namespaces: false
  translate_var: t
  enum_name: AppLocale
